[ StickerPack ] 뷰 구현
Team-Lecue/Lecue-Client pull request #21
Opened 2024-01-05 05:27 UTC by eunbeann

## 🔥 Related Issues

- close #12 

## ✅ 작업 내용

- [x] 퍼블리싱
- [x] 목 데이터 대충 구성해서 짜 넣기

## 📸 스크린샷 / GIF / Link

https://github.com/Team-Lecue/Lecue-Client/assets/65286685/28603de3-e517-4abf-b287-36f528ec45fd

## 📌 이슈 사항

- 현재 헤더의 bottom boarder 색이 반영되지 않았습니다. theme 반영하면서 수정하겠습니다.

2024-01-05 14:04 UTC, jungwoo3490 requested changes
선택한 스티커 state 관리하기 까다로웠을텐데 고생했어!!!

스타일 속성 관련 리뷰 제외한 리뷰들은 어디까지나 제안사항이야!! 확인해보고 은빈이 생각도 리뷰로 달아주면 좋을 것 같아 :)

2024-01-05 15:08 UTC, doyn511 approved these changes

2024-01-05 15:47 UTC, eunbeann commented on src/StickerPack/components/StickerList/index.tsx
> +  const { isSelectedId, setIsSelectedId } = props;
아 이거 컨벤션으로 얘기해보려고 했었는데!
요건 사실 완전히 취향 차이라고 생각해서용!!

맞추는 게 좋을까요?

2024-01-05 16:24 UTC, eunbeann commented on src/StickerPack/page/StickerPack/index.tsx
> +        />
[Lifting state up](https://react.dev/learn/sharing-state-between-components) 부모 컴포넌트에서 setter 함수를 내리는 것 자체에 대해서 괜찮다고 알고 있어서 그렇게 사용했거든!!

근데 넘겨주는 모양상 직관적으로 뭘 위해 넘겨주는지가 와닿지 않아서 다른 방식으로 넘겨주는게 더 좋을 것 같네!! 참고할게 고마워~~

*[Lifting state up]
부모 컴포넌트에서 자식 컴포넌트로 데이터를 변경하는 함수를 전달하여 부모 컴포넌트의 데이터를 변경하도록 하는 기술

2024-01-05 16:37 UTC, eunbeann commented on src/StickerPack/components/StickerList/StickerList.style.ts
> +  background: url(${({ url }) => url};);
이거이거 props로 상태 전달해주는 것이여가지고 컴포넌트에서 props 받아오는 것과 동일한 방식이여용!! 내가 작성한 건, props 객체에서 필요한 것만 구조분해할당으로 받아온 것!!
도리도리가 말해준 방식은 위에서 선언했던 친구를 참조할 때 써오는 방식이라 1만 되는 것입니당!

2024-01-05 16:40 UTC, eunbeann commented on src/StickerPack/components/StickerList/index.tsx
> +        <React.Fragment key={data.stickerCategory}>
나도 이번에 워닝떠서 에러 해결 구글링하다가 첨 알앗어....

2024-01-05 16:40 UTC, eunbeann commented on src/StickerPack/components/StickerList/StickerList.style.ts
> +export const StickerGridWrapper = styled.div`
오! 좋아 츄라이츄라이 해볼게 감사합니당 !!

2024-01-05 16:40 UTC, eunbeann commented on src/StickerPack/components/StickerList/StickerList.style.ts
> +export const StickerGridWrapper = styled.div`
오! 좋아 츄라이츄라이 해볼게 감사합니당 !!

2024-01-05 16:40 UTC, Arooming reviewed
너무 수고했어용! 다른 내용은 도리랑 짱우가 잘 적어줘서 간단한 의견 정도만 추가했습니당~

2024-01-05 16:40 UTC, Arooming commented on src/Router.tsx
> +        <Route path="/sticker-pack" element={<StickerPack />} />
웅웅 서버 명세서에 있는 url은 우리랑 통신할 때 사용할 주소이기 때문에 얘랑은 달라도 돼!

2024-01-05 16:40 UTC, Arooming commented on src/StickerPack/components/StickerList/index.tsx
> +  const { isSelectedId, setIsSelectedId } = props;
옹 나두 정우가 말한대로 하는 편이긴한데! 
컨벤션으로 맞춰도 좋을 것 같아용 한 번 이야기 나눠봅시당~!

2024-01-05 16:40 UTC, Arooming commented on src/StickerPack/components/StickerList/index.tsx
> +            ))}
`sticker.stickerId` 부분을 다른 코드로 대체하고 싶다고 생각한 이유를 알 수 있을까?!
단순히 id 값을 넘겨주는 부분이라고 생각할 수도 있는데..!!!

2024-01-05 16:42 UTC, eunbeann commented on src/StickerPack/components/StickerList/StickerList.style.ts
> +  gap: 2.15rem 1.6rem;
이거 묶는다는 말이 개행 순서 말하는 건가?!

2024-01-05 16:54 UTC, doyn511 commented on src/StickerPack/components/StickerList/index.tsx
> +  const { isSelectedId, setIsSelectedId } = props;
저는 비니 스타일로 더 많이 쓰는거 같아용.. 뭔가 props로 여러개를 받아와야 할 때 끝도없이 길어지는거 같아서 props로 받아오고 구조분해할당으로 쓰는편입니다!!

2024-01-05 16:54 UTC, doyn511 commented on src/Router.tsx
> +        <Route path="/sticker-pack" element={<StickerPack />} />
오 그렇군.. 오케이 확인!!!!

2024-01-05 16:55 UTC, doyn511 commented on src/StickerPack/components/StickerList/StickerList.style.ts
> +  background: url(${({ url }) => url};);
아아아아 이해완료!!! 고마와요❤️

2024-01-05 17:17 UTC, Arooming commented on src/StickerPack/components/StickerList/index.tsx
> +  const { isSelectedId, setIsSelectedId } = props;
옹 그렇군요!
개인적으로는 props로 받아오는 내용이 많아진다면 결국 구조분해할당을 위한 코드도 길어지는게 아닌지..! 하는 생각이 드는데 요거에 대해서는 어떻게 생각하는지 궁금해용!

++ 요 부분은 쩡우루밍/ 비니도리 일케 개인적인 취향으로 갈리는 것 같아서 각자의 방식 유지하는 걸로 할까용!? 
어차피 성능이나 코드 구현 상의 큰 문제는 없으니..!!!

2024-01-05 17:17 UTC, doyn511 commented on src/StickerPack/components/StickerList/index.tsx
> +            ))}
아아 다른 코드로 대체한다기보다는 항상 구조분해 할당으로 바로 stickerId, stickerImage 요것들만 뽑아서 써서 내가 고민해보고자 .. 해본 말이였어! 아루밍 말대로 단순히 값을 넘겨주는 부분이라 생각합니당 저도!

2024-01-05 17:52 UTC, jungwoo3490 commented on src/StickerPack/components/StickerList/StickerList.style.ts
> +  gap: 2.15rem 1.6rem;
정답!!

2024-01-06 08:07 UTC, eunbeann commented on src/StickerPack/components/StickerList/index.tsx
> +  const { isSelectedId, setIsSelectedId } = props;
그냥 컨벤션 없이 취향대로 찬성~~~~~

2024-01-06 08:12 UTC, doyn511 commented on src/StickerPack/components/StickerList/index.tsx
> +  const { isSelectedId, setIsSelectedId } = props;
저두 취향대로 찬성!!!!

2024-01-06 09:28 UTC, jungwoo3490 approved these changes

2024-01-06 10:46 UTC, jungwoo3490 approved these changes
💯💯💯

2024-01-06 14:34 UTC, merged