[ DetailPage ] 롤링페이퍼 상세 뷰 상단 축하글 UI 퍼블리싱
Team-Lecue/Lecue-Client pull request #24
Opened 2024-01-05 13:27 UTC by jungwoo3490

## 🔥 Related Issues

- close #20 

## ✅ 작업 내용

- [x] 상단 텍스트 롤링 슬라이드
- [x] 상단 축하글 부분

## 📸 스크린샷 / GIF / Link
isDarkMode: false (사용자가 롤링페이퍼를 흰색으로 만들었을 때)

https://github.com/Team-Lecue/Lecue-Client/assets/60962533/f8dc63db-29b6-4327-9976-f3cfe879efd8

isDarkMode: true (사용자가 롤링페이퍼를 검정색으로 만들었을 때)

https://github.com/Team-Lecue/Lecue-Client/assets/60962533/9cc17df9-2113-45ae-bace-fc81222cc1bf

## 📌 이슈 사항
- 원래 SlideBanner가 헤더 밑에 sticky된채로 유지되어야 하는데 그 부분은 뷰 구현 마저 끝난 뒤에 적용해보려고 합니다!!

- Props Drilling이 한 번 있는데 후에 이를 방지할 수 있는 더 나은 구조를 고민해보고 싶습니다...!!

2024-01-05 17:19 UTC, Arooming reviewed
수고했오!!!
개인적으로 의미없는 div는 React.Fragment로 바꿔주면 좋을 것 같은데..!!
첨부해둔 링크 한 번 봐주시구 결정은 쩡우의 판단에 맡길게용~~

2024-01-05 17:23 UTC, Arooming reviewed
아! 추가로 우리 S.네이밍을 사용하기로 했던 것 같은데 요거 사용하지 않고 구현한 이유가 따로 있을까용!?
큰 이유가 없다면 컨벤션 반영 부탁드립니당~~!!!

2024-01-05 18:01 UTC, jungwoo3490 commented on src/Detail/page/DetailPage.tsx
> +    </div>
요거는 그냥 자식 컴포넌트 띄우기 위한 초안이구 DetailPage는 추후에 DetailPageWrapper로 감싸줄 예정이었어!!

2024-01-05 18:02 UTC, jungwoo3490 commented on src/Detail/components/SlideBanner/index.tsx
> +  };
헉 따로 컨벤션이 없어서... 그렇게 수정 함 해보겟슴다!!

2024-01-06 08:18 UTC, doyn511 requested changes

2024-01-06 08:18 UTC, doyn511 commented on src/Detail/page/DetailPage.tsx
우리 파일 이름 다 index.tsx로 맞추는걸까?! 얘만 `index.tsx`가 아니라 `DetailPage.tsx`로 되어있길래!!

2024-01-06 10:10 UTC, eunbeann commented on src/Detail/components/SlideBanner/SlideBanner.style.ts
> +  /* column-gap: 0.6rem; */
주석처리 된 친구들은 지워주쟈아

2024-01-06 10:17 UTC, jungwoo3490 commented on src/Detail/components/SlideBanner/SlideBanner.style.ts
> +  /* column-gap: 0.6rem; */
어라 이거 예전 파일 내용인 것 같은데 지금은 지워져있어!!

2024-01-06 10:17 UTC, jungwoo3490 commented on src/Detail/components/BookInfoBox/BookInfoBox.style.ts
> +    isDarkMode ? theme.colors.MG : 'rgba(255, 255, 255, 0.3)'};
이거 머지한 뒤에 develop에서 받아와서 한꺼번에 수정하려고 했어! 리마인드 고마와~~!

2024-01-06 10:17 UTC, jungwoo3490 commented on src/Detail/components/BookInfoBox/BookInfoBox.style.ts
> +    isDarkMode ? theme.colors.BG : 'rgba(255, 255, 255, 0.8)'};
여기도!!

2024-01-06 10:18 UTC, jungwoo3490 commented on src/Detail/page/DetailPage.tsx
헉 조아요 이거 수정해둘겝!

2024-01-06 10:38 UTC, eunbeann approved these changes
🥇 🥇 🥇 🥇 🥇

2024-01-08 17:03 UTC, merged