[ Home ] 즐겨찾기 관련 기능 api 연결
Team-Lecue/Lecue-Client pull request #269
Opened 2024-03-15 09:48 UTC by Arooming

## 🔥 Related Issues

- close #259 

## ✅ 작업 내용

- [x] 즐겨찾기 삭제 api 연결
- [x] 즐겨찾기한 레큐북 목록을 불러오는 api 연결
- [x] 프로필 아이콘 클릭 시, 로그인 여부와 관계없이 마이페이지로 넘어가게 수정

## 📸 스크린샷 / GIF / Link

https://github.com/Team-Lecue/Lecue-Client/assets/80264647/4544b644-39df-4139-873f-b8e003ad3912

## 📌 이슈 사항
1. 로그인 분기없이 프로필 아이콘 클릭 시, 마이페이지로 넘어가게 수정했고, navigate의 state로 token 값을 넘겨주었습니다.
   아래 코드처럼 콘솔 값을 찍어서 state 값이 제대로 넘어오는지 확인했습니다.
   ```typescript
   const { state } = useLocation();
   console.log(state);
   ```

2. 즐겨찾기한 레큐북 목록을 불러오는 api 연결
   - 처음에는 기존 코드처럼 가장 상위의 page > Home 컴포넌트에서 호출하고자 했으나, 토큰이 있는 경우에만 해당 api를 호출해야 해서 data를 정의하는 과정에서 코드가 좀 꼬이더라구요.
      - 로그인하지 않은 경우에도 토큰을 필요로 하는 useGetFavorite()이 호출되면서 에러 발생.

   - 가장 상위 page > Home 컴포넌트에서는 토큰을 필요로 하지 않는 useGetLecueBook()만 호출,
   해당 훅의 리턴 값 중 하나인 isLoading만 사용하도록 수정했습니다.

   - 즐겨찾기, 인기 레큐북 리스트를 보여주는 컴포넌트
      - 커스텀 훅에서 리턴한 data를 `props`로 받아오는 코드 -> 해당 컴포넌트에서 `커스텀 훅을 직접 호출`하는 코드로 수정했습니다.
      - 현재 리턴해야 하는 컴포넌트가 `즐겨찾기한 레큐북`인 경우 useGetFavorite() 호출, 그렇지 않은 경우 useGetLecueBook() 호출
      
         ```typescript
           const isBookmark = title.includes('즐겨찾기');
           const { data } = isBookmark ? useGetFavorite() : useGetLecueBook();
         ```

2024-03-16 03:38 UTC, jungwoo3490 approved these changes
PR 내용이랑 코드 보면 분기처리해야할 경우도 많고 여러모로 신경 쓸 부분이 많았을 것 같은데 생각을 많이 하고 코드를 짰다는 생각이 들어요...!!
아름이 코드 보고 저도 많이 배우는 것 같습니다 ㅎㅎㅎ 고생했어요 👍🏻👍🏻👍🏻

2024-03-16 03:38 UTC, jungwoo3490 commented on src/Home/page/index.tsx
> +  const { isLoading: isLoadingLecueBook } = useGetLecueBook();
ASK: 이 부분이 아름이가 PR에 언급한 부분일까요?? 어떤 역할을 수행하는 라인인지 자세히 궁금해요!!

2024-03-16 13:12 UTC, Arooming commented on src/Home/page/index.tsx
> +  const { isLoading: isLoadingLecueBook } = useGetLecueBook();
아 요 부분은 현재 코드에서는 크게 중요하지 않은 부분인데요..! 

<br />

pr에서 `즐겨찾기한 레큐북 불러오는 api도 가장 상위의 page > Home 컴포넌트에서 호출하려고 했었다` 라고 했자나용?!
1. 이때 원래 코드 짜던 것처럼 구현하게 되면 변수명이 겹쳐서 요대로 구현할 수가 없어요!
```typescript
// 에러
const { isLoading, data } = useGetLecueBook();
const { isLoading, data } = useGetFavorite();
```

2. 그러면 변수명을 바꾸면 되지 않느냐..! 라고 생각할 수 있는데요, 
react-query에서 제공하는 반환 형식이 isLoading, data 요런 식으로 고정되어 있어서 
마음대로 변수 명을 바꾸면 `react-query에서는 알아볼 수 없는 형식이다!` 라는 에러를 뱉더라구요
```typescript
// 에러
const { isLoadingLecueBook, lecueBook } = useQuery({ ... });
```

3. 결국 아래의 코드는 한 컴포넌트 내에서 2개의 커스텀 훅을 호출하는 과정에서 
react-query에서 원하는 형식도 맞춰주고 + 변수 명도 다르게 구분지어준 결과라고 생각하면 될 것 같아요 !
isLoading, data를 받아올 건데 이번 훅에서는 `isLoading을 isLoadingLecueBook, data를 lecueBook라고 부를거야 ~`
라고 선언해준게 아래 코드입니당 ! (커스텀 훅 코드 안에 있어요)
```typescript
const { isLoading: isLoadingLecueBook, data: lecueBook } = useQuery({ ... });
```

4. 위에서 정의한 커스텀 훅을 불러올 때는 이렇게 불러오면 돼요 !
```typescript
const { isLoading: isLoadingLecueBook } = useGetLecueBook();
```

5. 사실 아래의 형식으로 불러와도 잘 동작합니다! 
단, 다른 커스텀 훅과 같이 불러올 때는 둘의 이름을 구분 짓기 위해 저렇게 구현했다는 점 ..! 참고해주시면 될 것 같아용 !!
```typescript
const { isLoading } = useGetLecueBook();
```

2024-03-16 15:33 UTC, eunbeann requested changes
이모저모 끙스러웟을텐데 넘 잘햇당! 짱 

++ 코드 돌려보면서 리뷰하다가 발견한건데 LecueBookList.style.ts의 IconWrapper는 button 타입이여도 좋겠어요

++ refetch와 invalidating이 조금 혼돈이 왔었는데 찾아보니 
**refetch**는 "나 지금 바로 이 데이터가 최신인지 확인해야 해" 할 때 사용. 즉각적이고 명시적인 데이터 새로고침이 필요할 때 선택.
**invalidateQueries**는 "이 데이터, 나중에 다시 볼 때 최신이어야 해" 할 때 사용. 데이터의 최신 상태를 유지해야 하지만, 꼭 지금 당장 새로고침할 필요는 없을 때 선택하는 방식
정도로 이해하면 되는 것 같아서(채찍피티 친구가 도와줫어요) 현재 상태에서는 refetch가 더 괜찮아보이네요오

2024-03-16 15:33 UTC, eunbeann commented on src/Home/hooks/useDeleteFavorite.ts
> +    onSuccess: () => location.reload(),
```suggestion
  onSuccess: () => {
  //  const queryClient = useQueryClient(); Import 해주세용
    queryClient.refetchQueries(['get-favorite'], { exact: true });
  },
```
deleteFavorite 함수가 성공적으로 실행되면, 해당 쿼리키를 가진 쿼리를 다시 실행 시키는 함수입니다!

 exact 옵션으로 정확하게 일치하는 쿼리 키를 가진 쿼리만 다시 실행하도록 한다고해용

 자연스럽게 데이터가 변화하니까 되니 한 번 고려 해보아도 좋겟어요!!!

2024-03-16 16:21 UTC, doyn511 reviewed
마이페이지까지 신경써주느라 고생했을텐데 아루밍 고마워요 !!

2024-03-16 16:21 UTC, doyn511 commented on src/Home/api/deleteFavorite.ts
ASK) 요 deleteFavorite랑 getFavorite는 마이페이지에서도 똑같은 방식으로 동작하는데 사용되는 페이지가 다를 때는 각각의 페이지에 api 폴더를 만들어서 넣어주는 것이 좋을까요..? 아니면 공통으로 사용할 수 있게 분리하는 것이 좋을까용...

2024-03-16 16:21 UTC, doyn511 commented on src/Home/components/NavigateLecueBook/index.tsx
> +    navigate('/mypage', { state: token });
P5) 마이페이지에서 useLocation으로 받아와서 state값을 사용하도록 반영해두었어요!

2024-03-17 03:09 UTC, jungwoo3490 commented on src/Home/page/index.tsx
> +  const { isLoading: isLoadingLecueBook } = useGetLecueBook();
오호 저렇게 중복될 경우에 네이밍을 다르게 가져갈수도 잇구나..... 좋은 거 배워가요!!! 😉

2024-03-18 18:50 UTC, Arooming commented on src/Home/hooks/useDeleteFavorite.ts
네!!!! 너무 좋아용 생각 못하고 넘겼던 부분인데 짚어줘서 고마뭐!!!!
나두 새로고침 하는거 좋지 않은 방식이라고 생각해서 비니가 추천해준 방식대로 수정해볼게용 !

2024-03-18 18:59 UTC, Arooming commented on src/Home/api/deleteFavorite.ts
헙!!! 마이페이지에서도 같이 사용하는 함수라면 공통으로 사용하는게 좋을 것 같아요!!
제가 공통 폴더로 빼놓을게용 !!

2024-03-18 19:04 UTC, Arooming commented on src/Home/components/NavigateLecueBook/index.tsx
> +    navigate('/mypage', { state: token });
네에 !!

2024-03-18 19:05 UTC, merged

2024-03-19 09:00 UTC, doyn511 commented on src/Home/api/deleteFavorite.ts
화긴~ 지금 하는 중인데 아루밍 덕분에 넘무 편하다요 ...... 엉엉 ㅜㅜ